name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - name: Set matrix by discovering workspaces (apps/ + packages/)
        id: set-matrix
        run: |
          dirs=$(find apps packages -type d -maxdepth 1 -mindepth 1)
          json=$(echo "$dirs" | jq -R -s -c 'split("\n")[:-1] | map({name: .})')
          echo "matrix=$json" >> $GITHUB_OUTPUT

  lint-build-test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.setup.outputs.matrix) }}

    defaults:
      run:
        working-directory: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint || echo "No lint script"

      - name: Build
        run: pnpm run build || echo "No build script"

      - name: Test
        run: pnpm run test || echo "No test script"
