name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo at root
        uses: actions/checkout@v4
        with:
          path: .  

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'  
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack and activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Type Check
        run: pnpm check-types

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
