name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout Repo at Root
        uses: actions/checkout@v4
        with:
          path: .  # ✅ Ensures correct working directory

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Generate Turbo Matrix from turbo.json
        id: set-matrix
        run: |
          MATRIX=$(jq -c '.tasks | to_entries | map({ name: .key })' turbo.json)
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml  # ✅ Explicitly cache at correct location

      - name: Install Dependencies at Root
        run: pnpm install --frozen-lockfile
        working-directory: ${{ github.workspace }}

  lint-build-test:
    needs: [setup, install]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include: ${{ fromJson(needs.setup.outputs.matrix) }}

    defaults:
      run:
        working-directory: ./${{ matrix.name }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Lint
        run: pnpm run lint || echo "No lint script"

      - name: Build
        run: pnpm run build || echo "No build script"

      - name: Test
        run: pnpm run test || echo "No test script"
