name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: 🔧 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps at root
        run: pnpm install --frozen-lockfile

  lint-build-test:
    name: Lint, Build & Test
    needs: install
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - apps/frontend
          - apps/backend
          - packages/config
          - packages/ui
          # Add more paths as needed

    defaults:
      run:
        working-directory: ${{ matrix.project }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: 🔧 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test || echo "No tests"
